print('SALÁRIO E VALORES DESCCONTADOS')
valorhora = float(input('Digite o valor que você ganha por hora: R$'))
trabalhohora = float(input('Digite a quantidade de horas trabalhadas por mês: '))
salariobruto = float(valorhora * trabalhohora)
ir = float((salariobruto * 11) / 100)
inss = float((salariobruto * 8) / 100)
sindicato = float((salariobruto * 5) / 100)
descontos = float(ir + inss + sindicato)
salarioliquido = float(salariobruto - descontos)
print(f'O seu Salário Bruto é R${salariobruto:.2f}')
print(f'O valor que você paga para o INSS é de: R${inss:.2f}')
print(f'O valor que você paga para o Sindicato é de: R${sindicato:.2f}')
print(f'O seu Salário Liquido é de: R${salarioliquido:.2f}')