print('NÚMEROS INTEIROS E NÚMEROS REAIS')
n1 = int(input('Digite um número Inteiro: '))
n2 = int(input('Digite outro número Inteiro: '))
n3 = float(input('Digite um número Real: '))
resultado1 = ((n1 * 2) * (n2 / 2))
resultado2 = ((n1 * 3) + n3)
resultado3 = (n3 ** 3)
print(f'O produto do dobro do primeiro com metade do segundo é {resultado1}')
print(f'A soma do triplo do primeiro com o terceiro é {resultado2}')
print(f'O terceiro elevado ao cubo é {resultado3}')